import { PlanChart } from 'types/chart';

export const SAMPLE_EMPTY_CHART: PlanChart = {
  UserId: 0,
  createdAt: '2023-10-18T11:26:22.545Z',
  id: 0,
  name: 'Make a plan together :)',
  orderNum: 0,
  removedAt: null,
  plans: [
    {
      PlanChartId: 0,
      createdAt: '2023-10-19T08:08:18.398Z',
      endHour: 8,
      endMin: 0,
      id: 0,
      name: '',
      notification: null,
      startHour: 7,
      startMin: 0,
      subPlans: [],
      updatedAt: null,
    },
    {
      PlanChartId: 0,
      createdAt: '2023-10-18T11:27:14.372Z',
      endHour: 10,
      endMin: 0,
      id: 0,
      name: '',
      notification: null,
      startHour: 8,
      startMin: 0,
      subPlans: [],
      updatedAt: null,
    },
    {
      PlanChartId: 0,
      createdAt: '2023-10-18T11:50:20.670Z',
      endHour: 12,
      endMin: 0,
      id: 0,
      name: '',
      notification: null,
      startHour: 10,
      startMin: 0,
      subPlans: [],
      updatedAt: null,
    },
    {
      PlanChartId: 0,
      createdAt: '2023-10-19T08:05:45.925Z',
      endHour: 15,
      endMin: 0,
      id: 0,
      name: '',
      notification: null,
      startHour: 12,
      startMin: 0,
      subPlans: [],
      updatedAt: null,
    },
    {
      PlanChartId: 0,
      createdAt: '2023-10-19T08:05:45.922Z',
      endHour: 16,
      endMin: 0,
      id: 0,
      name: '',
      notification: null,
      startHour: 15,
      startMin: 0,
      subPlans: [],
      updatedAt: null,
    },
    {
      PlanChartId: 0,
      createdAt: '2023-10-19T08:05:45.923Z',
      endHour: 18,
      endMin: 0,
      id: 0,
      name: '',
      notification: null,
      startHour: 16,
      startMin: 0,
      subPlans: [],
      updatedAt: null,
    },
    {
      PlanChartId: 0,
      createdAt: '2023-10-19T08:08:18.401Z',
      endHour: 19,
      endMin: 0,
      id: 0,
      name: '',
      notification: null,
      startHour: 18,
      startMin: 0,
      subPlans: [],
      updatedAt: null,
    },
    {
      PlanChartId: 0,
      createdAt: '2023-10-19T08:08:18.401Z',
      endHour: 23,
      endMin: 0,
      id: 0,
      name: '',
      notification: null,
      startHour: 19,
      startMin: 0,
      subPlans: [],
      updatedAt: null,
    },
    {
      PlanChartId: 0,
      createdAt: '2023-10-19T11:32:59.482Z',
      endHour: 7,
      endMin: 0,
      id: 0,
      name: '',
      notification: null,
      startHour: 23,
      startMin: 0,
      subPlans: [],
      updatedAt: null,
    },
  ],
  repeatDates: [],
  repeats: [0, 6, 1],
  updatedAt: null,
};
